name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # pin@v6.3.0
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

#      - name: test
#        env:
#          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
#        run: script/test
